import styled from 'styled-components';

export default styled.button`
  visibility: visible;
  font-family: Roboto, sans-serif;
  -webkit-font-smoothing: antialiased;
  font-size: 0.875rem;
  font-weight: 500;
  letter-spacing: 0.0892857143em;
  text-decoration: none;
  text-transform: uppercase;
  display: inline-flex;
  position: relative;
  align-items: center;
  justify-content: center;
  box-sizing: border-box;
  min-width: 64px;
  border: none;
  outline: none;
  line-height: inherit;
  user-select: none;
  -webkit-appearance: none;
  overflow: visible;
  vertical-align: middle;
  border-radius: 4px;
  padding: 0 16px 0 16px;
  box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14),
    0px 1px 5px 0px rgba(0, 0, 0, 0.12);
  transition: box-shadow 280ms cubic-bezier(0.4, 0, 0.2, 1);
  --mdc-ripple-left: 0;
  --mdc-ripple-top: 0;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  will-change: transform, opacity;
  height: 36px;
  background-color: var(--mdc-theme-primary, #6200ee);
  color: var(--mdc-theme-on-primary, #fff);
  --mdc-ripple-fg-opacity: 0.24;
  --mdc-ripple-fg-size: 56px;
  --mdc-ripple-fg-scale: 1.97577;
  --mdc-ripple-fg-translate-start: 24.3672px, -13.4727px;
  --mdc-ripple-fg-translate-end: 18.9922px, -10px;
  cursor: pointer;
`;
